;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        org-metaleft
        org-metaright
        org-self-insert-command
        org-shiftleft
        org-shiftright
        ))

(setq mc/cmds-to-run-once
      '(
        ))
